# Use an official Python runtime as a parent image
FROM python:3.12.3-slim

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install poppler-utils
RUN apt-get update && apt-get install -y poppler-utils

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run the application when the container launches
CMD ["flask", "run", "--host=0.0.0.0"]